<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fielddata</name>
   <tag></tag>
   <elementGuidId>b373d935-1d04-4868-8ef6-bb5a59072be2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>*//input[@name=&quot;${dynamicvariable}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>*//input[@name=&quot;${dynamicvariable}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
