<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Includevar</name>
   <tag></tag>
   <elementGuidId>2cb0a3ef-bc9a-4fc8-be9b-20790df04d05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;INCLUSIONS&quot;]//*[contains(text(),&quot;${var2}&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
