<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchLocation</name>
   <tag></tag>
   <elementGuidId>72d32518-4291-49a9-ab38-418c41947c3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;select2-drop&quot;]//*[@class=&quot;select2-search&quot;]//input</value>
   </webElementProperties>
</WebElementEntity>
