<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectAll</name>
   <tag></tag>
   <elementGuidId>37238cca-56c2-4065-8f1b-52c7ffb8240f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;INCLUSIONS&quot;]/div/div/div[1]/label/div/ins</value>
   </webElementProperties>
</WebElementEntity>
