<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StarSelection</name>
   <tag></tag>
   <elementGuidId>7c4c9b7e-930f-4cf8-84ff-f1486579619f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name=&quot;tourstars&quot;]//option[@value=&quot;${var1}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
